### ISSUE TITLE
Training from scratch.

### ISSUE THREAD

**Issue by asafjo23** [LukasHedegaard/continual-skeletons#10]
Hi There :-)

This is a great work.
As part of my thesis, I want to investigate the impact of the adjacencies matrices in the AGCN model.
Therefore I want to try to train it from scratch.
I already ran:
- kinetics400_prep
- bone_data_prep
- merge_joint_bone_data

scripts for the Kinetics dataset, but couldn't find an example of running the training script.
I'd be happy to get any help with it.

Thanks in advance,
Asaf,

**Comment by asafjo23** [comment]
Update: I managed to run the script.
I wanted to ask about a benchmarks of training time on CPU/GPU?

**Comment by LukasHedegaard** [comment]
Hi Asaf, glad you figured it out :-)
For future reference, the train and evaluation is invoked via the Ride command-line interface (see [example](https://ride.readthedocs.io/en/latest/common/main.html#example)).

On a single Nvidia RTX 2080 Ti GPU, our setup needed approx 2.5 hours per epoch on Kinetics (40 min per epoch on NTU60).

**Comment by asafjo23** [comment]
Thanks for answering!
I ran the following: models/s_tr/scripts/train_kinetics.py with the right changes to run the AGCN model.
