### ISSUE TITLE
How to get the model output

### ISSUE THREAD

**Issue by sha310139** [LukasHedegaard/continual-skeletons#12]
Hello, thanks for your amazing work!

Since I'm not familiar with the framework of ride package
I want to ask if I can get the output of the model directly in the code
Just like the following format:

```
model = CoStGcn(args)
output = model(input)
```

I have read your ride repo but didn't find the answer
I look forward to receiving your response. Thank you!

**Comment by LukasHedegaard** [comment]
Hi @sha310139, I looks like you figured it out. Let me know if you bump into issues again.
