### ISSUE TITLE
Evaluation Error on Kinetics dataset

### ISSUE THREAD

**Issue by iazdan** [LukasHedegaard/continual-skeletons#8]
Running "python models/cost_gcn/scripts/evaluate_kinetics.py"  throws this error:

with open(path, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'datasets/kinetics/classes.yaml'

Could you please provide the classes.yaml file? 

Thanks

**Comment by LukasHedegaard** [comment]
Thank you for bringing this to my attention. I have the missing classes.yaml files for each of the datasets in PR #9
